window.alert("que mas");
window.alert("que mas");
window.alert("que mas");
window.alert("que mas");
window.alert("que mas");
window.alert("que mas");
window.alert("que mas");
window.alert("que mas");
window.alert("que mas");